### ISSUE TITLE
Website: Fix Accomplishment Bar

### ISSUE THREAD

**Issue by eksno** [startino/futino#98]
**Is your feature request related to a problem? Please describe.**
This bar has false information and scales badly on desktop.

![Image](https://github.com/Futino/futino/assets/33558637/3e4c2880-bfde-4490-a9d1-68990035a977)

**Describe the solution you'd like**
Make it scale matching the width of the others, along with replace the data with real data so we don't have to hesitate when publishing.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by antopiahk** [comment]
what real data were you thinking? We've got 3 sites made... idk any other stat heh
